@extends('layouts.app')
@section('content')
@php($editing = $history->exists)
<div class="container py-4"><h3>{{ $editing ? 'Editar' : 'Registrar' }} Historia Clínica Inicial</h3><form method="POST" action="{{ $editing ? route('initial-histories.update', $history) : route('initial-histories.store') }}" class="card card-body shadow-sm">@csrf @if($editing)@method('PUT')@endif
<div class="row g-3">
@unless($editing)<div class="col-md-8"><label class="form-label">Paciente</label><select name="patient_id" class="form-select" required><option value="">Seleccione</option>@foreach($patients as $patient)<option value="{{ $patient->id }}" @selected((string)old('patient_id',$history->patient_id)===(string)$patient->id)>{{ $patient->full_name }} · {{ $patient->dni }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Fecha de registro</label><input type="date" name="recorded_at" class="form-control" value="{{ old('recorded_at', optional($history->recorded_at)->format('Y-m-d')) }}" required></div>@else<div class="col-12 alert alert-light">Paciente: <strong>{{ $history->patient->full_name }}</strong> · Fecha histórica: {{ $history->recorded_at->format('d/m/Y') }}. La fecha y las referencias de laboratorio no se modifican.</div>@endunless
<div class="col-md-6"><label class="form-label">Nefrólogo responsable</label><select name="nephrologist_id" class="form-select"><option value="">Seleccione</option>@foreach($nephrologists as $doctor)<option value="{{ $doctor->id }}" @selected((string)old('nephrologist_id',$history->nephrologist_id)===(string)$doctor->id)>{{ $doctor->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Primera hemodiálisis</label><input type="date" name="first_hemodialysis_date" class="form-control" value="{{ old('first_hemodialysis_date', optional($history->first_hemodialysis_date)->format('Y-m-d')) }}"></div><div class="col-md-3"><label class="form-label">Grupo sanguíneo</label><input name="blood_type" class="form-control" value="{{ old('blood_type',$history->blood_type) }}"></div>
@foreach(['personal_history'=>'Antecedentes personales','family_history'=>'Antecedentes familiares','ckd_etiology'=>'Etiología de ERC','transfusion_history'=>'Transfusiones','allergies'=>'Alergias','previous_renal_therapy'=>'Terapia renal previa','clinical_exam'=>'Examen clínico','vascular_access_notes'=>'Observaciones del acceso vascular'] as $field=>$label)<div class="col-md-6"><label class="form-label">{{ $label }}</label><textarea name="{{ $field }}" class="form-control" rows="3">{{ old($field,$history->$field) }}</textarea></div>@endforeach
<div class="col-md-4"><label class="form-label">Diuresis residual (ml/24h)</label><input type="number" step="0.01" min="0" name="residual_diuresis" class="form-control" value="{{ old('residual_diuresis',$history->residual_diuresis) }}"></div>
<div class="col-12"><label class="form-label">Comorbilidades</label><div class="d-flex flex-wrap gap-3">@foreach(\App\Http\Controllers\InitialClinicalHistoryController::COMORBIDITIES as $value)<label><input type="checkbox" name="comorbidities[]" value="{{ $value }}" @checked(in_array($value,old('comorbidities',$history->comorbidities??[])))> {{ $value }}</label>@endforeach</div></div>
<div class="col-12"><label class="form-label">Inmunizaciones</label><div class="d-flex flex-wrap gap-3">@foreach(\App\Http\Controllers\InitialClinicalHistoryController::IMMUNIZATIONS as $value)<label><input type="checkbox" name="immunizations[]" value="{{ $value }}" @checked(in_array($value,old('immunizations',$history->immunizations??[])))> {{ $value }}</label>@endforeach</div></div>
</div><div class="mt-4"><button class="btn btn-primary">Guardar</button> <a class="btn btn-outline-secondary" href="{{ route('initial-histories.index') }}">Cancelar</a></div></form></div>
@endsection
