<div class="center"><b>ANEXO N.° 3</b><h3>CONSENTIMIENTO INFORMADO PARA TRATAMIENTO DE HEMODIÁLISIS</h3></div>
<p><b>Fecha:</b> {{ $consent->consented_at->format('d/m/Y') }}<br><b>Nombres y apellidos del paciente:</b> {{ $consent->patient->full_name }}<br><b>DNI N.°:</b> {{ $consent->patient->dni }} &nbsp; <b>Edad:</b> {{ $consent->patient->birth_date?->diffInYears($consent->consented_at) ?? $consent->patient->age }} &nbsp; <b>Domicilio:</b> {{ $consent->patient->address }}</p>
<p>Usted ha sido diagnosticada(o) con Enfermedad Renal Crónica Terminal, para lo cual tendrá que continuar con sus sesiones de hemodiálisis como tratamiento sustitutivo renal. Dicho procedimiento se realiza a través de un dializador con la finalidad de limpiar la sangre de las sustancias y del exceso de líquidos que sus riñones no son capaces de eliminar.</p>
<p>Este procedimiento se realiza a través de un acceso vascular como catéter venoso central, fístula arterio-venosa o injerto. Si tiene una fístula o injerto se realizarán dos punciones en cada sesión; si porta un catéter se efectuará la conexión al sistema de hemodiálisis.</p>
<p>Además de las sesiones de hemodiálisis, deberá colaborar activamente con la dieta y medicación prescritas. El tratamiento busca mejorar su calidad de vida, no equivale a la curación de su enfermedad ni evita por completo su progresión o patologías asociadas.</p>
<p>Entre las complicaciones posibles se encuentran náuseas, vómitos, cefalea, hipotensión o hipertensión arterial, hemorragia, alteraciones visuales, arritmias, dolor torácico y calambres. En la conexión pueden presentarse ruptura del filtro o líneas, coagulación del circuito, hemólisis o entrada de aire. También pueden ocurrir hipersensibilidad, infección del acceso vascular o contaminación del agua o líquido de diálisis.</p>
<p>Por lo expuesto, dejo constancia de que:</p><ol type="a"><li>He sido informado(a) respecto a mi enfermedad y las complicaciones del tratamiento.</li><li>En pleno uso de mis facultades, comprendo la finalidad del tratamiento propuesto y sus posibles complicaciones.</li><li>He recibido una explicación clara y sencilla, y se absolvieron las consultas planteadas.</li></ol>
<p><b>Decisión:</b> {{ $consent->accepted ? 'ACEPTO EL TRATAMIENTO DE HEMODIÁLISIS' : 'NO ACEPTO EL TRATAMIENTO DE HEMODIÁLISIS' }}</p>
<table class="signature-row"><tr>
    <td><div class="signature-space">@if($consent->patient_signature_path)<img class="signature-image" src="{{ storage_path('app/public/'.$consent->patient_signature_path) }}">@elseif($consent->fingerprint_path)<img class="signature-image" src="{{ storage_path('app/public/'.$consent->fingerprint_path) }}">@endif</div><div class="signature-line">Firma y/o huella del paciente<br>DNI: {{ $consent->patient->dni }}</div></td>
    <td><div class="signature-space">@if($consent->representative_signature_path)<img class="signature-image" src="{{ storage_path('app/public/'.$consent->representative_signature_path) }}">@endif</div><div class="signature-line">Firma y/o huella del familiar o apoderado<br>{{ $consent->representative_name ?: 'Nombres y apellidos' }}<br>DNI: {{ $consent->representative_document ?: '________________' }}</div></td>
</tr></table>
<div class="physician-signature"><div class="signature-space">@include('pdf.partials.digital_stamp', ['user' => $consent->physician, 'role' => 'doctor'])</div><div class="signature-line">Firma y sello del médico profesional<br>{{ $consent->physician?->name }}</div></div>
<div class="footer">Versión {{ $consent->version }}</div>
