@extends('layouts.app')

@section('content')
@php($editing = $consultation->exists)
<div class="container-fluid">
    <div class="d-flex justify-content-between mb-3"><h3 class="fw-bold">Plantilla de consulta nefrológica</h3><a href="{{ route('consultations.index') }}" class="btn btn-outline-secondary">Volver</a></div>
    @if($errors->any())<div class="alert alert-danger"><strong>Revise los datos:</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ $editing ? route('consultations.update', $consultation) : route('consultations.store') }}">@csrf @if($editing)@method('PUT')@endif
        <div class="card shadow-sm mb-3"><div class="card-header fw-bold">Datos de atención</div><div class="card-body"><div class="row g-3">
            <div class="col-md-5"><label class="form-label">Paciente *</label><select name="patient_id" class="form-select" required><option value="">Seleccione...</option>@foreach($patients as $patient)<option value="{{ $patient->id }}" @selected(old('patient_id', $consultation->patient_id) == $patient->id)>{{ $patient->full_name }} — {{ $patient->dni }}</option>@endforeach</select></div>
            <div class="col-md-4"><label class="form-label">Médico</label><select name="doctor_id" class="form-select"><option value="">Usuario actual</option>@foreach($doctors as $doctor)<option value="{{ $doctor->id }}" @selected(old('doctor_id', $consultation->doctor_id) == $doctor->id)>{{ $doctor->name }}</option>@endforeach</select></div>
            <div class="col-md-3"><label class="form-label">Fecha *</label><input type="date" name="consultation_date" class="form-control" required value="{{ old('consultation_date', optional($consultation->consultation_date)->format('Y-m-d')) }}"></div>
            @foreach(['blood_pressure'=>'Presión arterial','weight'=>'Peso (kg)','temperature'=>'Temperatura (°C)','heart_rate'=>'Frecuencia cardíaca','oxygen_saturation'=>'Sat. O₂ (%)'] as $field=>$label)<div class="col"><label class="form-label">{{ $label }}</label><input name="{{ $field }}" type="{{ $field === 'blood_pressure' ? 'text' : 'number' }}" step="{{ in_array($field, ['weight','temperature']) ? '0.1' : '1' }}" class="form-control" value="{{ old($field, $consultation->$field) }}"></div>@endforeach
        </div></div></div>
        <div class="card shadow-sm mb-3"><div class="card-header fw-bold">Evaluación nefrológica</div><div class="card-body"><div class="row g-3">
            @foreach(['reason'=>'Motivo de consulta','current_illness'=>'Enfermedad actual','history'=>'Antecedentes','physical_exam'=>'Examen físico','diagnosis'=>'Diagnóstico','treatment_plan'=>'Plan / indicaciones','observations'=>'Observaciones'] as $field=>$label)<div class="col-md-6"><label class="form-label">{{ $label }}</label><textarea name="{{ $field }}" rows="3" class="form-control">{{ old($field, $consultation->$field ?: ($field === 'diagnosis' ? 'ENFERMEDAD RENAL CRÓNICA ESTADIO 5 (N18.0)' : '')) }}</textarea></div>@endforeach
        </div></div></div>
        <div class="card shadow-sm mb-3"><div class="card-header d-flex justify-content-between"><strong>Receta médica — medicamentos</strong><button type="button" id="addMedication" class="btn btn-sm btn-outline-primary">Agregar fila</button></div><div class="table-responsive"><table class="table mb-0"><thead class="table-light"><tr><th>Código FUA</th><th style="width:40%">Descripción</th><th>C</th><th>Prescrita</th><th>Cantidad entregada</th><th></th></tr></thead><tbody id="medications">
            @foreach(old('medications', $medications->toArray()) as $i=>$medication)<tr><td><input class="form-control" name="medications[{{ $i }}][fua_code]" value="{{ $medication['fua_code'] ?? '' }}"></td><td><input required class="form-control" name="medications[{{ $i }}][description]" value="{{ $medication['description'] ?? '' }}"></td><td><input class="form-control" name="medications[{{ $i }}][c]" value="{{ $medication['c'] ?? '' }}"></td><td><input type="number" min="0" step="0.01" class="form-control" name="medications[{{ $i }}][prescribed_quantity]" value="{{ $medication['prescribed_quantity'] ?? 0 }}"></td><td><input type="number" min="0" step="0.01" class="form-control" name="medications[{{ $i }}][delivered_quantity]" value="{{ $medication['delivered_quantity'] ?? 0 }}"></td><td><button type="button" class="btn btn-outline-danger remove-row">×</button></td></tr>@endforeach
        </tbody></table></div></div>
        <div class="d-flex gap-2 justify-content-end"><button class="btn btn-success px-4">Guardar consulta</button>@if($editing)<a target="_blank" href="{{ route('consultations.prescription.pdf', $consultation) }}" class="btn btn-danger">Generar PDF de receta</a>@endif</div>
    </form>
</div>
@endsection
@push('scripts')<script>
document.addEventListener('DOMContentLoaded', () => { const body=document.getElementById('medications'); document.getElementById('addMedication').onclick=()=>{const i=body.children.length; body.insertAdjacentHTML('beforeend', `<tr><td><input class="form-control" name="medications[${i}][fua_code]"></td><td><input required class="form-control" name="medications[${i}][description]"></td><td><input class="form-control" name="medications[${i}][c]"></td><td><input type="number" min="0" step="0.01" value="0" class="form-control" name="medications[${i}][prescribed_quantity]"></td><td><input type="number" min="0" step="0.01" value="0" class="form-control" name="medications[${i}][delivered_quantity]"></td><td><button type="button" class="btn btn-outline-danger remove-row">×</button></td></tr>`)}; body.addEventListener('click',e=>{if(e.target.classList.contains('remove-row')&&body.children.length>1)e.target.closest('tr').remove()}); });
</script>@endpush
