<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:30px 36px}body{font-family:DejaVu Sans,sans-serif;font-size:11px;color:#172033}.header{text-align:center;border-bottom:2px solid #183b6b;padding-bottom:12px}.header h1{font-size:20px;margin:0;color:#183b6b}.header p{margin:4px}.meta{width:100%;margin:18px 0;border-collapse:collapse}.meta td{padding:5px;border:1px solid #ccd5df}.label{font-weight:bold;background:#eef3f8;width:18%}table.meds{width:100%;border-collapse:collapse;margin-top:10px}.meds th,.meds td{border:1px solid #60758d;padding:7px}.meds th{background:#183b6b;color:white;text-transform:uppercase;font-size:9px}.num{text-align:center}.section{font-weight:bold;color:#183b6b;margin-top:20px}.box{border:1px solid #ccd5df;min-height:55px;padding:8px;white-space:pre-line}.signatures{margin-top:70px;width:100%;text-align:center}.signatures td{width:50%}.line{border-top:1px solid #222;padding-top:5px;margin:0 30px}.footer{position:fixed;bottom:0;text-align:center;width:100%;font-size:8px;color:#667}
</style></head><body>
<div class="header"><h1>RECETA MÉDICA</h1><p><strong>Consulta nefrológica</strong></p><p>{{ $consultation->sede?->name }}</p></div>
<table class="meta"><tr><td class="label">Paciente</td><td>{{ $consultation->patient->full_name }}</td><td class="label">Fecha</td><td>{{ $consultation->consultation_date->format('d/m/Y') }}</td></tr><tr><td class="label">DNI</td><td>{{ $consultation->patient->dni ?: '—' }}</td><td class="label">H. clínica</td><td>{{ $consultation->patient->medical_history_number ?: '—' }}</td></tr><tr><td class="label">Diagnóstico</td><td colspan="3">{{ $consultation->diagnosis ?: '—' }}</td></tr></table>
<div class="section">Rp.</div><table class="meds"><thead><tr><th>Código FUA</th><th>Descripción</th><th>C</th><th>Prescrita</th><th>Cantidad entregada</th></tr></thead><tbody>@foreach($consultation->medications as $medication)<tr><td class="num">{{ $medication->fua_code }}</td><td>{{ $medication->description }}</td><td class="num">{{ $medication->c }}</td><td class="num">{{ rtrim(rtrim(number_format($medication->prescribed_quantity, 2, '.', ''), '0'), '.') }}</td><td class="num">{{ rtrim(rtrim(number_format($medication->delivered_quantity, 2, '.', ''), '0'), '.') }}</td></tr>@endforeach</tbody></table>
<div class="section">Indicaciones</div><div class="box">{{ $consultation->treatment_plan ?: 'Sin indicaciones adicionales.' }}</div>
<table class="signatures"><tr><td><div class="line">Firma del paciente / responsable</div></td><td><div class="line"><strong>{{ $consultation->doctor?->name ?: 'Médico tratante' }}</strong><br>CMP: {{ $consultation->doctor?->license_number ?: '________' }} &nbsp; RNE: {{ $consultation->doctor?->specialty_number ?: '________' }}<br>Firma y sello</div></td></tr></table>
<div class="footer">Receta generada el {{ now()->format('d/m/Y H:i') }} — Consulta N.° {{ $consultation->id }}</div>
</body></html>
