<?php
namespace Tests\Feature;
use App\Models\Eq5dAssessment;use App\Models\Order;use App\Models\Patient;use App\Models\PsychologyAssessment;use App\Models\Sede;use App\Models\SocialWorkAssessment;use App\Models\User;use App\Support\ClinicalService;use Database\Seeders\RolesAndPermissionsSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
class PsychologySocialFormatsTest extends TestCase
{
 use RefreshDatabase; private Sede $sede; private Patient $patient;
 protected function setUp():void{parent::setUp();$this->sede=Sede::create(['name'=>'Multisectorial','code'=>'MUL']);$this->seed(RolesAndPermissionsSeeder::class);$this->patient=Patient::factory()->create(['sede_id'=>$this->sede->id]);}
 public function test_psychologist_records_official_fields_and_eq5d():void{$user=$this->professional('psicologo');$order=$this->order(ClinicalService::PSYCHOLOGY,$user,'PSI');$this->actingAs($user)->withSession($this->session())->post(route('psychology.store',$order),['assessment_date'=>'2026-08-25','consultation_reason'=>'Adaptación al tratamiento','behavior_observation'=>'Colaborador','psychological_tests'=>'Entrevista clínica','psychological_diagnosis'=>'Ansiedad','treatment_plan'=>'Psicoterapia breve','recommendations'=>'Red de apoyo'])->assertRedirect();$item=PsychologyAssessment::firstOrFail();$this->actingAs($user)->withSession($this->session())->post(route('eq5d.store',$item),['assessed_at'=>'2026-08-25','mobility'=>1,'self_care'=>2,'usual_activities'=>2,'pain_discomfort'=>1,'anxiety_depression'=>2,'health_scale'=>75])->assertRedirect();$eq=Eq5dAssessment::firstOrFail();$this->assertSame('12212',$eq->health_state);$this->assertSame(75,$eq->health_scale);}
 public function test_social_worker_records_all_official_sections():void{$user=$this->professional('trabajo.social');$order=$this->order(ClinicalService::SOCIAL_WORK,$user,'SOC');$this->actingAs($user)->withSession($this->session())->post(route('social-work.store',$order),['assessment_date'=>'2026-08-25','social_evaluation'=>'Red limitada','family_evaluation'=>'Familia nuclear','housing_evaluation'=>'Propia','employment_evaluation'=>'Independiente','economic_evaluation'=>'Ingresos variables','social_diagnosis'=>'Riesgo medio','general_measures'=>'Orientación','specific_measures'=>'Seguimiento'])->assertRedirect();$this->assertDatabaseHas('social_work_assessments',['order_id'=>$order->id,'social_diagnosis'=>'Riesgo medio']);}
 public function test_sector_separation_returns_403():void{$psych=$this->professional('psicologo');$social=$this->professional('trabajo.social');$socialOrder=$this->order(ClinicalService::SOCIAL_WORK,$social,'SOC2');$this->actingAs($psych)->withSession($this->session())->get(route('social-work.create',$socialOrder))->assertForbidden();}
 private function professional(string $username):User{$u=User::where('username',$username)->firstOrFail();$u->sedes()->syncWithoutDetaching([$this->sede->id]);return $u;}
 private function order(string $type,User $user,string $code):Order{return Order::create(['sede_id'=>$this->sede->id,'patient_id'=>$this->patient->id,'assigned_professional_id'=>$user->id,'created_by'=>$user->id,'codigo_unico'=>$code,'attention_type'=>$type,'status'=>'PENDING','fecha_orden'=>'2026-08-01','due_date'=>'2026-08-30','period_key'=>'2026-Q3']);}
 private function session():array{return ['current_sede_id'=>$this->sede->id,'current_sede_name'=>$this->sede->name];}
}
