<?php
namespace Tests\Feature;
use App\Models\{DialysisMachine,LaboratoryOrder,MachineDisinfection,Order,Patient,PatientClinicalEvent,Sede,Test,User,ViralInfectionInvestigation,WaterQualityRecord};use App\Support\ClinicalService;use Database\Seeders\RolesAndPermissionsSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
class RemainingAnnexesTest extends TestCase{
 use RefreshDatabase;private Sede $sede;private User $admin;private Patient $patient;
 protected function setUp():void{parent::setUp();$this->sede=Sede::create(['name'=>'Final','code'=>'FIN']);$this->seed(RolesAndPermissionsSeeder::class);$this->admin=User::factory()->create();$this->admin->assignRole('admin');$this->admin->sedes()->attach($this->sede);$this->patient=Patient::factory()->create(['sede_id'=>$this->sede->id]);}
 public function test_patient_reports_derive_new_patient_and_store_append_only_events():void{Order::create(['sede_id'=>$this->sede->id,'patient_id'=>$this->patient->id,'codigo_unico'=>'HD-F','attention_type'=>ClinicalService::HEMODIALYSIS,'fecha_orden'=>'2026-08-10']);$this->actingAs($this->admin)->withSession($this->session())->get(route('homologation.patients',['month'=>'2026-08']))->assertOk()->assertSee($this->patient->full_name);$this->post(route('homologation.patient-events.store',$this->patient),['type'=>'HOSPITALIZED','occurred_at'=>'2026-08-20','reason'=>'Infección','facility'=>'Hospital'])->assertRedirect();$this->assertDatabaseHas('patient_clinical_events',['patient_id'=>$this->patient->id,'recorded_by'=>$this->admin->id]);}
 public function test_water_and_machine_disinfection_keep_daily_history_and_uniqueness():void{$this->actingAs($this->admin)->withSession($this->session())->post(route('homologation.machines.store'),['code'=>'M-01','brand_model'=>'4008S','station'=>'1']);$machine=DialysisMachine::firstOrFail();$this->post(route('homologation.water.store'),['measured_at'=>'2026-08-25 08:00','sampling_point'=>'Ósmosis','ph'=>7.1,'total_chlorine'=>0.01]);$this->post(route('homologation.disinfection.store'),['dialysis_machine_id'=>$machine->id,'work_date'=>'2026-08-25','shift'=>'1','started_at'=>'08:00','finished_at'=>'09:00','method'=>'Química']);$this->assertSame(1,WaterQualityRecord::count());$this->assertSame(1,MachineDisinfection::count());}
 public function test_epidemiology_links_existing_serology_by_reference():void{$area=\App\Models\Area::create(['name'=>'Serología']);$test=Test::create(['area_id'=>$area->id,'name'=>'Antígeno de superficie hepatitis B (HBsAg)','unit'=>'COI','type'=>'text']);$lab=LaboratoryOrder::create(['patient_id'=>$this->patient->id,'patient_name'=>'P','sampled_at'=>'2026-08-20','period'=>'S','status'=>'completed']);$result=$lab->items()->create(['test_id'=>$test->id,'result_value'=>'Reactivo','completed_at'=>'2026-08-20']);$this->actingAs($this->admin)->withSession($this->session())->post(route('homologation.epidemiology.store'),['patient_id'=>$this->patient->id,'investigated_at'=>'2026-08-25','suspected_infection'=>'VHB'])->assertRedirect();$item=ViralInfectionInvestigation::firstOrFail();$this->assertSame([$result->id],$item->laboratoryResults()->pluck('laboratory_order_items.id')->all());}
 public function test_sector_user_is_forbidden():void{$u=User::factory()->create();$u->assignRole('psicologo');$u->sedes()->attach($this->sede);$this->actingAs($u)->withSession($this->session())->get(route('homologation.technical'))->assertForbidden();}
 private function session():array{return['current_sede_id'=>$this->sede->id,'current_sede_name'=>$this->sede->name];}
}
