<!doctype html>
<html lang="es"><head><meta charset="utf-8"><style>
@page{size:A4 portrait;margin:1.8cm}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;font-size:7px;color:#000;margin:0;text-transform:uppercase}.page{height:252mm;border:2px solid #111;padding:8px;position:relative;page-break-inside:avoid;overflow:hidden}.page+.page{page-break-before:always}.brand{height:68px;padding:0 8px;text-align:left}.brand-logo{display:block;width:520px;height:60px;object-fit:contain;object-position:left center}.brand-block{display:inline-block;height:48px;vertical-align:top;color:#fff;padding:8px 10px;font-weight:bold}.peru{background:#df0712;font-size:14px;padding-top:14px}.minsa{background:#777;font-size:14px;line-height:13px}.sis{background:#999;font-size:12px;padding-top:17px}.doc-title{text-align:center;font-weight:bold;font-size:9px;margin-top:-10px}.number-label{background:#a8a8a8;display:table;min-width:200px;margin:0 auto;text-align:center;font-size:6px;font-weight:bold;padding:3px}.number{border:1px solid #333;display:table;min-width:200px;margin:0 auto 5px;text-align:center;font-size:10px;font-weight:bold;padding:4px}.grid{border-collapse:collapse;width:100%;table-layout:fixed}.grid th,.grid td{border:1px solid #333;padding:2px;vertical-align:middle}.grid th,.section{background:#a8a8a8;text-align:center;font-weight:bold}.subhead{background:#bebebe}.label{font-size:5px;text-align:center}.value{text-align:center;font-size:7px;font-weight:bold;min-height:12px}.h16{height:16px}.h22{height:22px}.diagnosis{table-layout:auto}.diagnosis td{height:27px}.diagnosis-number,.diagnosis-code,.diagnosis .diagnosis-type{white-space:nowrap}.diagnosis-number{width:1%}.diagnosis-code{width:13%}.diagnosis .diagnosis-type{width:1%;padding-left:2px;padding-right:2px;text-align:center}.center{text-align:center}.right{text-align:right}.tiny{font-size:5px}.signatures{position:absolute;left:8px;right:8px;bottom:18px;width:calc(100% - 16px);height:220px;border-collapse:separate;table-layout:fixed}.signatures.posterior{bottom:8px;height:180px}.signatures td{width:33.333%;height:220px;padding:10px;text-align:center;vertical-align:bottom}.signatures.posterior td{height:180px}.signatures .fingerprint{border:1px solid #333}.signature-label{display:block;margin-top:8px;font-size:5px;font-weight:bold;text-align:center}.black{background:#000!important;color:#fff}.second-title{text-align:center;font-size:5px;margin-bottom:28px}.medications td,.procedures td{height:19px}.description{text-align:left}.observations{height:18px}
</style></head><body>
@php
    $patient = $fua->order?->patient;
    $date = $fua->order?->fecha_orden ? \Carbon\Carbon::parse($fua->order->fecha_orden) : $fua->created_at;
    $doctorName = $responsible?->name ?: $configuration->responsible_name;
    $doctorDni = $responsible?->dni ?: $configuration->responsible_document;
    $doctorCmp = $responsible?->license_number ?: $configuration->responsible_college_number;
    $doctorSpecialty = $responsible?->profession ?: $configuration->responsible_specialty;
@endphp
<div class="page">
 <div class="brand">@if($logoData)<img src="{{ $logoData }}" class="brand-logo" alt="Logo institucional">@else<span class="brand-block peru">PERÚ</span><span class="brand-block minsa">Ministerio<br>de Salud</span><span class="brand-block sis">Seguro Integral de Salud</span>@endif</div>
 <div class="doc-title">FORMATO DE ATENCIÓN</div><div class="number-label">NÚMERO DE FORMATO</div><div class="number">{{ $fua->number }}</div>
 <table class="grid"><tr><th width="20%" class="label">CODIGO IPRESS</th><th width="52%" class="label">NOMBRE DE IPRESS QUE REALIZA LA ATENCION</th><th class="label">SUBSANACION<br>N° FORMATO ATENCION PARA SUBSANACION</th></tr><tr class="h22"><td class="value">{{ $configuration->ipress_code }}</td><td class="value">{{ $configuration->ipress_name ?: $fua->order?->sede?->name }}</td><td class="value">{{ $fua->correctedFua?->number }}</td></tr></table>
 <table class="grid"><tr><th colspan="3" class="label">FECHA DE ATENCIÓN</th><th class="label">HORA</th><th class="label">N° HISTORIA CLÍNICA</th><th colspan="2" class="label">IDENTIFICACIÓN</th><th colspan="2" class="label">RÉGIMEN</th></tr><tr><td class="label subhead">DÍA</td><td class="label subhead">MES</td><td class="label subhead">AÑO</td><td rowspan="2" class="value">{{ $fua->order?->medical?->hora_inicial ? substr($fua->order->medical->hora_inicial,0,5) : '' }}</td><td rowspan="2" class="value">{{ $patient?->medical_history_number ?: $patient?->dni }}</td><td class="label subhead">TD</td><td class="label subhead">N° DOCUMENTO</td><td class="label subhead">SUBSIDIADO</td><td class="value">{{ $patient?->insurance_regime === 'SUBSIDIADO' ? 'X' : '' }}</td></tr><tr><td class="value">{{ $date->format('d') }}</td><td class="value">{{ $date->format('m') }}</td><td class="value">{{ $date->format('Y') }}</td><td class="value">2</td><td class="value">{{ $patient?->dni }}</td><td class="tiny center subhead">SEMICONTRIBUTIVO</td><td class="value">{{ $patient?->insurance_regime === 'SEMICONTRIBUTIVO' ? 'X' : '' }}</td></tr></table>
 <table class="grid"><tr><th colspan="2" class="label">APELLIDO PATERNO</th><th colspan="2" class="label">APELLIDO MATERNO</th></tr><tr><td colspan="2" class="value">{{ $patient?->surname }}</td><td colspan="2" class="value">{{ $patient?->last_name }}</td></tr><tr><th colspan="2" class="label">PRIMER NOMBRE</th><th colspan="2" class="label">OTROS NOMBRES</th></tr><tr><td colspan="2" class="value">{{ $patient?->first_name }}</td><td colspan="2" class="value">{{ $patient?->other_names }}</td></tr></table>
 <table class="grid" style="margin-top:6px"><tr><th colspan="4">TIPO DE PRESTACION</th></tr><tr class="h22"><td>CONSULTA EXTERNA</td><td width="9%"></td><td>ATENCION DE PROCEDIMIENTOS AMBULATORIOS</td><td width="9%" class="value">{{ $fua->type === 'HEMODIALYSIS' ? 'X' : '' }}</td></tr></table>
 <table class="grid diagnosis" style="margin-top:6px"><tr><th colspan="6">DIAGNOSTICOS</th></tr><tr><th class="diagnosis-number">N°</th><th>DESCRIPCION</th><th class="diagnosis-code">CIE - 10</th><th colspan="3">TIPO DX</th></tr>@for($i=1;$i<=6;$i++)<tr><td class="diagnosis-number">{{ $i }}</td><td>{{ $i===1 ? $configuration->diagnosis_name : '' }}</td><td class="value diagnosis-code">{{ $i===1 ? $configuration->diagnosis_code : '' }}</td><td class="diagnosis-type">{{ $i===1 ? '' : 'P' }}</td><td class="diagnosis-type">D</td><td class="diagnosis-type">{{ $i===1 ? '' : 'R' }}</td></tr>@endfor</table>
 <table class="grid" style="margin-top:6px"><tr><th width="14%">N° DNI</th><th>NOMBRE DEL RESPONSABLE DE LA ATENCION</th><th width="20%">N° COLEGIATURA</th></tr><tr class="h22"><td class="value">{{ $doctorDni ?: 'AUN NO SE REGISTRA MEDICO' }}</td><td class="value">{{ $doctorName ?: 'AUN NO SE REGISTRA MEDICO' }}</td><td class="value">{{ $doctorCmp ?: 'AUN NO SE REGISTRA MEDICO' }}</td></tr></table>
 <table class="grid"><tr><th width="23%">RESPONSABLE DE LA ATENCION</th><td class="center">1</td><th width="20%">ESPECIALIDAD</th><td class="value">{{ mb_strtoupper($doctorSpecialty ?: 'NEFROLOGIA') }}</td><td width="30%" rowspan="2"></td></tr><tr><td colspan="4" class="tiny">1=MEDICO 2=FARMACEUTICO 3=ODONTOLOGO 4=BIOLOGO 5=OBSTETRIZ 6=ENFERMERA 7=TRABAJADOR SOCIAL 8=PSICOLOGO 9=TECNOLOGO MEDICO 10=NUTRICIONISTA 11=TECNICO ENFERMERIA 12=AUXILIAR DE ENFERMERIA</td></tr></table>
 <table class="signatures"><tr><td>@include('pdf.partials.digital_stamp', ['user' => $responsible, 'name' => $doctorName, 'license' => $doctorCmp, 'role' => 'doctor'])</td><td><span class="signature-label">FIRMA DEL ASEGURADO O APODERADO</span></td><td class="fingerprint"><span class="signature-label">HUELLA DIGITAL DEL ASEGURADO O<br>APODERADO</span></td></tr></table>
</div>
<div class="page">
 <div class="second-title">FORMATO DE ATENCION<br><span style="float:left">(CARA POSTERIOR)</span></div>
 <table class="grid medications"><tr><th colspan="8" class="black">MEDICAMENTOS</th></tr><tr><th>CODIGO</th><th>DESCRIPCION</th><th>C. PRESCRITA</th><th>C. ENTREGADA</th><th>CODIGO</th><th>DESCRIPCION</th><th>C. PRESCRITA</th><th>C. ENTREGADA</th></tr>@for($i=0;$i<9;$i++)@php $leftMedication=$medications[$i]??null; $rightMedication=$medications[$i+9]??null; @endphp<tr><td>{{ $leftMedication['code']??'' }}</td><td class="description">{{ $leftMedication['description']??'' }}</td><td class="center">{{ $leftMedication['quantity']??'' }}</td><td class="center">{{ $leftMedication['quantity']??'' }}</td><td>{{ $rightMedication['code']??'' }}</td><td class="description">{{ $rightMedication['description']??'' }}</td><td class="center">{{ $rightMedication['quantity']??'' }}</td><td class="center">{{ $rightMedication['quantity']??'' }}</td></tr>@endfor</table>
 <table class="grid procedures" style="margin-top:7px"><tr><th colspan="8" class="black">PROCEDIMIENTOS: SESIONES DE HEMODIALISIS /EXAMENES AUXILIARES / CONSULTAS</th></tr><tr><th width="9%">CODIGO</th><th>DESCRIPCION</th><th width="12%">C. PRESCRITA</th><th width="12%">C. EJECUTADA</th><th width="9%">CODIGO</th><th>DESCRIPCION</th><th width="12%">C. PRESCRITA</th><th width="12%">C. EJECUTADA</th></tr>@for($i=0;$i<12;$i++)@php $left=$procedures[$i]??null; $right=$procedures[$i+12]??null; @endphp<tr><td>{{ $left['code']??'' }}</td><td>{{ $left['description']??'' }}</td><td class="center">{{ $left['quantity']??'' }}</td><td class="center">{{ $left['quantity']??'' }}</td><td>{{ $right['code']??'' }}</td><td>{{ $right['description']??'' }}</td><td class="center">{{ $right['quantity']??'' }}</td><td class="center">{{ $right['quantity']??'' }}</td></tr>@endfor</table>
 <table class="grid" style="margin-top:7px"><tr><th class="black">OBSERVACIONES</th></tr><tr><td class="observations">{{ $fua->order?->medical?->indicaciones }}</td></tr></table>
 <table class="signatures posterior"><tr><td>@include('pdf.partials.digital_stamp', ['user' => $responsible, 'name' => $doctorName, 'license' => $doctorCmp, 'role' => 'doctor'])</td><td><span class="signature-label">FIRMA DEL ASEGURADO O APODERADO</span></td><td class="fingerprint"><span class="signature-label">HUELLA DIGITAL DEL ASEGURADO O APODERADO</span></td></tr></table>
</div></body></html>
