<!doctype html>
<html lang="es"><head><meta charset="utf-8"><style>
@page{margin:18px 22px}body{font-family:DejaVu Sans,sans-serif;font-size:9px;color:#111}.title{text-align:center;font-size:15px;font-weight:bold}.subtitle{text-align:center;font-size:10px;margin:3px 0 10px}.box{border:1px solid #222;margin-bottom:6px}.head{background:#e8eef7;border-bottom:1px solid #222;padding:4px;font-weight:bold}.grid{width:100%;border-collapse:collapse}.grid td{border:1px solid #777;padding:5px;vertical-align:top}.label{font-size:7px;color:#444;text-transform:uppercase}.value{font-size:10px;font-weight:bold;margin-top:3px}.checks{font-size:10px;line-height:1.8}.signature{height:70px;text-align:center;vertical-align:bottom!important}.footer{text-align:center;color:#555;font-size:7px;margin-top:8px}
</style></head><body>
<div class="title">FORMATO ÚNICO DE ATENCIÓN - FUA</div>
<div class="subtitle">Seguro Integral de Salud · {{ $fua->type === 'NEPHROLOGY' ? 'Consulta nefrológica' : ($fua->type === 'CORRECTION' ? 'Subsanación' : 'Atención de hemodiálisis') }}</div>
<div class="box"><div class="head">I. DATOS DE LA IPRESS</div><table class="grid"><tr><td width="28%"><div class="label">Código IPRESS</div><div class="value">{{ $configuration->ipress_code ?: '—' }}</div></td><td><div class="label">Nombre de la IPRESS</div><div class="value">{{ $configuration->ipress_name ?: ($fua->order?->sede?->name ?? '—') }}</div></td><td width="25%"><div class="label">Número de FUA</div><div class="value">{{ $fua->number }}</div></td></tr></table></div>
<div class="box"><div class="head">II. DATOS DEL ASEGURADO / USUARIO</div><table class="grid"><tr><td colspan="2"><div class="label">Apellidos y nombres</div><div class="value">{{ $fua->order?->patient?->full_name ?? '—' }}</div></td><td width="24%"><div class="label">Documento de identidad</div><div class="value">{{ $fua->order?->patient?->dni ?? '—' }}</div></td></tr><tr><td><div class="label">Historia clínica</div><div class="value">{{ $fua->order?->patient?->medical_history_number ?? '—' }}</div></td><td><div class="label">Fecha de nacimiento</div><div class="value">{{ $fua->order?->patient?->birth_date ? \Carbon\Carbon::parse($fua->order->patient->birth_date)->format('d/m/Y') : '—' }}</div></td><td><div class="label">Sexo</div><div class="value">{{ $fua->order?->patient?->sex ?? '—' }}</div></td></tr></table></div>
<div class="box"><div class="head">III. DATOS DE LA ATENCIÓN</div><table class="grid"><tr><td><div class="label">Fecha de atención</div><div class="value">{{ $fua->order?->fecha_orden ? \Carbon\Carbon::parse($fua->order->fecha_orden)->format('d/m/Y') : $fua->created_at->format('d/m/Y') }}</div></td><td><div class="label">Turno</div><div class="value">{{ $fua->order?->turno ?? '—' }}</div></td><td><div class="label">Sala / módulo</div><div class="value">{{ $fua->order?->sala ?? '—' }}</div></td><td><div class="label">Duración</div><div class="value">{{ $fua->order?->horas_dialisis ? $fua->order->horas_dialisis.' horas' : '—' }}</div></td></tr><tr><td colspan="4"><div class="label">Tipo de atención</div><div class="checks">{{ $fua->type === 'HEMODIALYSIS' ? '☒' : '☐' }} Hemodiálisis &nbsp;&nbsp; {{ $fua->type === 'NEPHROLOGY' ? '☒' : '☐' }} Consulta nefrológica &nbsp;&nbsp; {{ $fua->type === 'CORRECTION' ? '☒' : '☐' }} Subsanación</div></td></tr></table></div>
<div class="box"><div class="head">IV. DIAGNÓSTICO</div><table class="grid"><tr><td width="25%"><div class="label">Código CIE-10</div><div class="value">{{ $configuration->diagnosis_code }}</div></td><td><div class="label">Descripción</div><div class="value">{{ $configuration->diagnosis_name }}</div></td></tr></table></div>
<div class="box"><div class="head">V. RESPONSABLE DE LA ATENCIÓN</div><table class="grid"><tr><td><div class="label">Profesional responsable</div><div class="value">{{ $configuration->responsible_name ?: '—' }}</div></td><td><div class="label">DNI</div><div class="value">{{ $configuration->responsible_document ?: '—' }}</div></td><td><div class="label">Colegiatura</div><div class="value">{{ $configuration->responsible_college_number ?: '—' }}</div></td><td><div class="label">Especialidad</div><div class="value">{{ $configuration->responsible_specialty ?: '—' }}</div></td></tr><tr><td colspan="2" class="signature">Firma y sello del responsable</td><td colspan="2" class="signature">Firma / huella del asegurado</td></tr></table></div>
<div class="footer">Documento generado por HEMODIAL · {{ now()->format('d/m/Y H:i') }} · FUA {{ $fua->number }}</div>
</body></html>
