<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::create('patient_clinical_events',function(Blueprint $t){$t->id();$t->foreignId('patient_id')->constrained()->cascadeOnDelete();$t->foreignId('sede_id')->constrained()->cascadeOnDelete();$t->foreignId('recorded_by')->nullable()->constrained('users')->nullOnDelete();$t->string('type',20);$t->dateTime('occurred_at');$t->string('facility')->nullable();$t->string('reason')->nullable();$t->text('notes')->nullable();$t->timestamps();$t->index(['sede_id','type','occurred_at'],'patient_event_report_idx');$t->unique(['patient_id','type','occurred_at'],'patient_event_unique');});
  Schema::create('dialysis_machines',function(Blueprint $t){$t->id();$t->foreignId('sede_id')->constrained()->cascadeOnDelete();$t->string('code');$t->string('serial_number')->nullable();$t->string('brand_model')->nullable();$t->string('station')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['sede_id','code'],'machine_sede_code_unq');});
  Schema::create('water_quality_records',function(Blueprint $t){$t->id();$t->foreignId('sede_id')->constrained()->cascadeOnDelete();$t->foreignId('responsible_id')->nullable()->constrained('users')->nullOnDelete();$t->dateTime('measured_at');$t->string('sampling_point');foreach(['temperature','conductivity','hardness','total_chlorine','free_chlorine','ph'] as $c)$t->decimal($c,10,3)->nullable();$t->string('appearance')->nullable();$t->text('observations')->nullable();$t->timestamps();$t->unique(['sede_id','measured_at','sampling_point'],'water_measurement_unq');});
  Schema::create('machine_disinfections',function(Blueprint $t){$t->id();$t->foreignId('dialysis_machine_id')->constrained()->cascadeOnDelete();$t->foreignId('responsible_id')->nullable()->constrained('users')->nullOnDelete();$t->date('work_date');$t->string('shift',20);$t->time('started_at');$t->time('finished_at');$t->string('method');$t->string('disinfectant')->nullable();$t->text('observations')->nullable();$t->timestamps();$t->unique(['dialysis_machine_id','work_date','shift'],'machine_disinfection_unq');});
  Schema::create('viral_infection_investigations',function(Blueprint $t){$t->id();$t->foreignId('patient_id')->constrained()->cascadeOnDelete();$t->foreignId('sede_id')->constrained()->cascadeOnDelete();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->date('investigated_at');$t->string('suspected_infection');$t->date('symptom_onset')->nullable();$t->text('clinical_manifestations')->nullable();$t->text('dialysis_history')->nullable();$t->text('risk_factors')->nullable();$t->text('contacts')->nullable();$t->text('control_measures')->nullable();$t->string('classification')->nullable();$t->text('observations')->nullable();$t->timestamps();$t->unique(['patient_id','investigated_at','suspected_infection'],'viral_investigation_unique');});
  Schema::create('viral_investigation_laboratory_results',function(Blueprint $t){$t->unsignedBigInteger('viral_infection_investigation_id');$t->unsignedBigInteger('laboratory_order_item_id');$t->foreign('viral_infection_investigation_id','viral_inv_lab_inv_fk')->references('id')->on('viral_infection_investigations')->cascadeOnDelete();$t->foreign('laboratory_order_item_id','viral_inv_lab_result_fk')->references('id')->on('laboratory_order_items')->restrictOnDelete();$t->primary(['viral_infection_investigation_id','laboratory_order_item_id'],'viral_inv_lab_primary');});
 }
 public function down():void{Schema::dropIfExists('viral_investigation_laboratory_results');Schema::dropIfExists('viral_infection_investigations');Schema::dropIfExists('machine_disinfections');Schema::dropIfExists('water_quality_records');Schema::dropIfExists('dialysis_machines');Schema::dropIfExists('patient_clinical_events');}
};
