@extends('layouts.app')
@section('content')
<div class="container-fluid py-4 px-lg-4">
 <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><span class="badge bg-primary bg-opacity-10 text-primary">BLOQUE 10</span><h2 class="mb-1">Controles diarios de Enfermería y descartes</h2><p class="text-muted mb-0">La información clínica y los consumos se consolidan desde cada sesión.</p></div><form class="d-flex gap-2" method="GET"><input class="form-control" type="date" name="date" value="{{ $date }}"><button class="btn btn-primary">Consultar</button></form></div>
 <div class="row g-3 mb-4"><div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-muted">Sesiones del día</div><div class="display-6 fw-bold">{{ $orders->count() }}</div></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-muted">Descartes de dializador</div><div class="display-6 fw-bold text-danger">{{ $orders->sum(fn($o)=>$o->disposableDiscards->where('category',\App\Models\DisposableDiscard::DIALYZER)->count()) }}</div></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-muted">Descartes de líneas</div><div class="display-6 fw-bold text-warning">{{ $orders->sum(fn($o)=>$o->disposableDiscards->where('category',\App\Models\DisposableDiscard::BLOOD_LINES)->count()) }}</div></div></div></div></div>
 <div class="d-flex flex-wrap gap-2 mb-3">@can('annexes.nursing.print')<a target="_blank" class="btn btn-outline-danger" href="{{ route('nursing-annexes.discards.pdf',['category'=>\App\Models\DisposableDiscard::DIALYZER,'date'=>$date]) }}">PDF Anexo 11-A</a><a target="_blank" class="btn btn-outline-warning" href="{{ route('nursing-annexes.discards.pdf',['category'=>\App\Models\DisposableDiscard::BLOOD_LINES,'date'=>$date]) }}">PDF Anexo 11-B</a><a target="_blank" class="btn btn-outline-primary" href="{{ route('nursing-annexes.care.pdf',['date'=>$date]) }}">PDF Anexo 12</a>@endcan</div>
 @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
 <div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Sesión</th><th>Paciente</th><th>Dializador</th><th>Líneas registradas</th><th>Enfermería</th><th>Descartes</th></tr></thead><tbody>@forelse($orders as $order)@php($lines=$order->hemodialysisMaterialConsumptions->first(fn($c)=>str_contains(mb_strtolower($c->material?->name??''),'línea')))<tr><td><strong>{{ $order->codigo_unico }}</strong><br><small>{{ $order->turno }} · Puesto {{ $order->nurse?->puesto??'—' }}</small></td><td>{{ $order->patient->full_name }}<br><small class="text-muted">HC {{ $order->patient->medical_history_number }}</small></td><td>{{ $order->nurse?->filtro?:'SIN REGISTRO' }}<br><small>{{ $order->nurse?->aspecto_dializador }}</small></td><td>{{ $lines?->quantity??'SIN CONSUMO' }} {{ $lines?->material?->unit }}</td><td>@if($order->nurse)<span class="badge bg-success">Registrada</span>@else<span class="badge bg-secondary">Pendiente</span>@endif</td><td>@foreach([\App\Models\DisposableDiscard::DIALYZER=>'Dializador',\App\Models\DisposableDiscard::BLOOD_LINES=>'Líneas'] as $category=>$label)@php($discard=$order->disposableDiscards->firstWhere('category',$category))@if($discard)<span class="badge bg-danger me-1">{{ $label }}: {{ $discard->discard_reason }}</span>@else @can('annexes.nursing.record')<button class="btn btn-sm btn-outline-secondary me-1" data-bs-toggle="collapse" data-bs-target="#discard-{{ $order->id }}-{{ $category }}">+ {{ $label }}</button>@endcan @endif<div class="collapse mt-2" id="discard-{{ $order->id }}-{{ $category }}"><form class="card card-body bg-light" method="POST" action="{{ route('nursing-annexes.discards.store',$order) }}">@csrf<input type="hidden" name="category" value="{{ $category }}"><input type="datetime-local" name="discarded_at" value="{{ $date }}T12:00" class="form-control form-control-sm mb-2" required><input name="lot_number" class="form-control form-control-sm mb-2" placeholder="Lote, si está disponible"><select name="discard_reason" class="form-select form-select-sm mb-2" required><option value="">Motivo de descarte</option><option>Uso único completado</option><option>Coagulación</option><option>Ruptura o fuga</option><option>Contaminación</option><option>Deterioro</option><option>Otro</option></select><input name="final_condition" class="form-control form-control-sm mb-2" placeholder="Condición final"><button class="btn btn-sm btn-danger">Registrar descarte</button></form></div>@endforeach</td></tr>@empty<tr><td colspan="6" class="text-center py-5 text-muted">No existen sesiones de hemodiálisis en la fecha seleccionada.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
