<?php
namespace App\Http\Controllers;
use App\Models\Order; use App\Models\PsychologyAssessment; use App\Services\MultisectorialOrderService; use App\Services\PdfBrandingService; use App\Support\ClinicalService; use App\Support\CurrentSede; use Barryvdh\DomPDF\Facade\Pdf; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class PsychologyAssessmentController extends Controller
{
    public function __construct(){ $this->middleware('permission:psychology.view')->only(['index','show']); $this->middleware('permission:psychology.create')->only(['create','store']); $this->middleware('permission:psychology.update')->only(['edit','update']); $this->middleware('permission:psychology.print')->only('pdf'); }
    public function index(){ return view('psychology.index',['items'=>PsychologyAssessment::with(['order.patient','eq5dAssessment'])->whereHas('order',fn($q)=>$q->where('sede_id',CurrentSede::id()))->latest('assessment_date')->paginate(20),'pendingOrders'=>Order::with('patient')->where(['sede_id'=>CurrentSede::id(),'attention_type'=>ClinicalService::PSYCHOLOGY])->whereDoesntHave('psychologyAssessment')->get()]); }
    public function create(Order $order){$this->authorizeOrder($order); return view('psychology.form',['item'=>new PsychologyAssessment(['assessment_date'=>today()]),'order'=>$order->load('patient')]);}
    public function store(Request $request,Order $order){$this->authorizeOrder($order);$data=$this->validated($request);$item=DB::transaction(function()use($order,$data,$request){$locked=Order::lockForUpdate()->findOrFail($order->id);abort_if($locked->psychologyAssessment()->exists(),409);$item=PsychologyAssessment::create($data+['order_id'=>$locked->id,'created_by'=>$request->user()->id,'updated_by'=>$request->user()->id]);$locked->update(['status'=>MultisectorialOrderService::COMPLETED,'completed_at'=>now()]);return $item;});return redirect()->route('psychology.show',$item);}
    public function show(PsychologyAssessment $psychology){$this->authorizeOrder($psychology->order);$psychology->load('order.patient.sede','order.assignedProfessional','eq5dAssessment');return view('psychology.show',['item'=>$psychology]);}
    public function edit(PsychologyAssessment $psychology){$this->authorizeOrder($psychology->order);return view('psychology.form',['item'=>$psychology,'order'=>$psychology->order->load('patient')]);}
    public function update(Request $request,PsychologyAssessment $psychology){$this->authorizeOrder($psychology->order);$data=$this->validated($request);unset($data['assessment_date']);$psychology->update($data+['updated_by'=>$request->user()->id]);return redirect()->route('psychology.show',$psychology);}
    public function pdf(PsychologyAssessment $psychology,PdfBrandingService $branding){$this->authorizeOrder($psychology->order);$psychology->load('order.patient.sede','order.assignedProfessional','eq5dAssessment');return Pdf::loadView('psychology.pdf',$branding->data()+['item'=>$psychology])->setPaper('a4')->stream("anexo-8-{$psychology->id}.pdf");}
    private function validated(Request $r){return $r->validate(['assessment_date'=>'required|date','consultation_reason'=>'required|string','behavior_observation'=>'nullable|string','psychological_tests'=>'nullable|string','psychological_diagnosis'=>'required|string','treatment_plan'=>'nullable|string','recommendations'=>'nullable|string']);}
    private function authorizeOrder(Order $o){abort_unless($o->attention_type===ClinicalService::PSYCHOLOGY&&(int)$o->sede_id===(int)CurrentSede::id()&&(auth()->user()->can('orders.edit')||(int)$o->assigned_professional_id===(int)auth()->id()),403);}
}
