<?php
namespace App\Http\Controllers;
use App\Models\{DialysisMachine,MachineDisinfection,Order,Patient,PatientClinicalEvent,ViralInfectionInvestigation,WaterQualityRecord};use App\Services\{LaboratoryResultSnapshotService,PdfBrandingService};use App\Support\{ClinicalService,CurrentSede};use Barryvdh\DomPDF\Facade\Pdf;use Illuminate\Http\Request;
class RemainingAnnexController extends Controller{
 public function __construct(){$this->middleware('permission:homologation.reports.view')->only(['patientReports','vascularAccess']);$this->middleware('permission:homologation.events.manage')->only('storePatientEvent');$this->middleware('permission:homologation.technical.manage')->only(['technical','storeWater','storeMachine','storeDisinfection']);$this->middleware('permission:homologation.epidemiology.manage')->only(['epidemiology','storeEpidemiology']);$this->middleware('permission:homologation.print')->only('pdf');}
 public function patientReports(Request $r){$month=$r->get('month',today()->format('Y-m'));[$from,$to]=$this->month($month);$new=Patient::where('sede_id',CurrentSede::id())->whereHas('orders',fn($q)=>$q->where('attention_type',ClinicalService::HEMODIALYSIS)->whereBetween('fecha_orden',[$from,$to]))->withMin(['orders as first_hd_date'=>fn($q)=>$q->where('attention_type',ClinicalService::HEMODIALYSIS)],'fecha_orden')->get()->filter(fn($p)=>$p->first_hd_date>=$from&&$p->first_hd_date<=$to);$events=PatientClinicalEvent::with('patient')->where('sede_id',CurrentSede::id())->whereBetween('occurred_at',[$from,$to->endOfDay()])->get();return view('remaining-annexes.patient-reports',compact('month','new','events'));}
 public function storePatientEvent(Request $r,Patient $patient){abort_unless((int)$patient->sede_id===(int)CurrentSede::id(),403);$d=$r->validate(['type'=>'required|in:HOSPITALIZED,DISCHARGED','occurred_at'=>'required|date','facility'=>'nullable|string|max:255','reason'=>'required|string|max:255','notes'=>'nullable|string']);PatientClinicalEvent::create($d+['patient_id'=>$patient->id,'sede_id'=>$patient->sede_id,'recorded_by'=>$r->user()->id]);return back()->with('success','Evento registrado.');}
 public function vascularAccess(Request $r){$month=$r->get('month',today()->format('Y-m'));[$from,$to]=$this->month($month);$rows=Order::with(['patient','nurse'])->where('sede_id',CurrentSede::id())->where('attention_type',ClinicalService::HEMODIALYSIS)->whereBetween('fecha_orden',[$from,$to])->whereHas('nurse')->latest('fecha_orden')->get()->unique('patient_id');return view('remaining-annexes.vascular',compact('rows','month'));}
 public function technical(Request $r){$date=$r->get('date',today()->format('Y-m-d'));return view('remaining-annexes.technical',['date'=>$date,'machines'=>DialysisMachine::where('sede_id',CurrentSede::id())->get(),'water'=>WaterQualityRecord::with('responsible')->where('sede_id',CurrentSede::id())->whereDate('measured_at',$date)->get(),'disinfections'=>MachineDisinfection::with(['machine','responsible'])->whereHas('machine',fn($q)=>$q->where('sede_id',CurrentSede::id()))->whereDate('work_date',$date)->get()]);}
 public function storeMachine(Request $r){$d=$r->validate(['code'=>'required|string|max:50','serial_number'=>'nullable|string|max:100','brand_model'=>'nullable|string|max:150','station'=>'nullable|string|max:50']);DialysisMachine::updateOrCreate(['sede_id'=>CurrentSede::id(),'code'=>$d['code']],$d+['is_active'=>true]);return back();}
 public function storeWater(Request $r){$d=$r->validate(['measured_at'=>'required|date','sampling_point'=>'required|string|max:120','temperature'=>'nullable|numeric','conductivity'=>'nullable|numeric','hardness'=>'nullable|numeric','total_chlorine'=>'nullable|numeric','free_chlorine'=>'nullable|numeric','ph'=>'nullable|numeric','appearance'=>'nullable|string','observations'=>'nullable|string']);WaterQualityRecord::create($d+['sede_id'=>CurrentSede::id(),'responsible_id'=>$r->user()->id]);return back();}
 public function storeDisinfection(Request $r){$d=$r->validate(['dialysis_machine_id'=>'required|exists:dialysis_machines,id','work_date'=>'required|date','shift'=>'required|string','started_at'=>'required|date_format:H:i','finished_at'=>'required|date_format:H:i|after:started_at','method'=>'required|string','disinfectant'=>'nullable|string','observations'=>'nullable|string']);$machine=DialysisMachine::findOrFail($d['dialysis_machine_id']);abort_unless((int)$machine->sede_id===(int)CurrentSede::id(),403);MachineDisinfection::create($d+['responsible_id'=>$r->user()->id]);return back();}
 public function epidemiology(){return view('remaining-annexes.epidemiology',['patients'=>Patient::where('sede_id',CurrentSede::id())->orderBy('surname')->get(),'items'=>ViralInfectionInvestigation::with('patient')->where('sede_id',CurrentSede::id())->latest('investigated_at')->paginate(20)]);}
 public function storeEpidemiology(Request $r,LaboratoryResultSnapshotService $labs){$d=$r->validate(['patient_id'=>'required|exists:patients,id','investigated_at'=>'required|date','suspected_infection'=>'required|string','symptom_onset'=>'nullable|date','clinical_manifestations'=>'nullable|string','dialysis_history'=>'nullable|string','risk_factors'=>'nullable|string','contacts'=>'nullable|string','control_measures'=>'nullable|string','classification'=>'nullable|string','observations'=>'nullable|string']);$p=Patient::findOrFail($d['patient_id']);abort_unless((int)$p->sede_id===(int)CurrentSede::id(),403);$item=ViralInfectionInvestigation::create($d+['sede_id'=>$p->sede_id,'created_by'=>$r->user()->id]);$refs=$labs->latestValidFor($p,$item->investigated_at)->filter(fn($x)=>str($x->test->name)->lower()->contains(['vih','hepatitis','hbs','hcv','htlv','sífilis']));$item->laboratoryResults()->attach($refs->modelKeys());return back();}
 public function pdf(Request $r,string $annex,PdfBrandingService $branding){abort_unless(in_array($annex,['13a','13b','13c','14','15','16','17']),404);$month=$r->get('month',today()->format('Y-m'));[$from,$to]=$this->month($month);$data=match($annex){'13a'=>Patient::withMin(['orders as first_hd_date'=>fn($q)=>$q->where('attention_type',ClinicalService::HEMODIALYSIS)],'fecha_orden')->where('sede_id',CurrentSede::id())->get()->filter(fn($p)=>$p->first_hd_date&&$p->first_hd_date>=$from&&$p->first_hd_date<=$to),'13b'=>PatientClinicalEvent::with('patient')->where(['sede_id'=>CurrentSede::id(),'type'=>PatientClinicalEvent::HOSPITALIZED])->whereBetween('occurred_at',[$from,$to])->get(),'13c'=>PatientClinicalEvent::with('patient')->where(['sede_id'=>CurrentSede::id(),'type'=>PatientClinicalEvent::DISCHARGED])->whereBetween('occurred_at',[$from,$to])->get(),'14'=>WaterQualityRecord::with('responsible')->where('sede_id',CurrentSede::id())->whereBetween('measured_at',[$from,$to])->get(),'15'=>MachineDisinfection::with(['machine','responsible'])->whereHas('machine',fn($q)=>$q->where('sede_id',CurrentSede::id()))->whereBetween('work_date',[$from,$to])->get(),'16'=>Order::with(['patient','nurse'])->where('sede_id',CurrentSede::id())->whereBetween('fecha_orden',[$from,$to])->whereHas('nurse')->latest('fecha_orden')->get()->unique('patient_id'),'17'=>ViralInfectionInvestigation::with(['patient','laboratoryResults.test'])->where('sede_id',CurrentSede::id())->whereBetween('investigated_at',[$from,$to])->get()};return Pdf::loadView('remaining-annexes.generic-pdf',$branding->data()+compact('annex','data','month'))->setPaper('a4','landscape')->stream("anexo-$annex.pdf");}
 private function month(string $month):array{$from=\Carbon\Carbon::createFromFormat('Y-m',$month)->startOfMonth();return[$from->copy(),$from->copy()->endOfMonth()];}
}
