<?php
namespace App\Http\Controllers;
use App\Models\Order;use App\Models\SocialWorkAssessment;use App\Services\MultisectorialOrderService;use App\Services\PdfBrandingService;use App\Support\ClinicalService;use App\Support\CurrentSede;use Barryvdh\DomPDF\Facade\Pdf;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class SocialWorkAssessmentController extends Controller
{
 public function __construct(){$this->middleware('permission:social_work.view')->only(['index','show']);$this->middleware('permission:social_work.create')->only(['create','store']);$this->middleware('permission:social_work.update')->only(['edit','update']);$this->middleware('permission:social_work.print')->only('pdf');}
 public function index(){return view('social-work.index',['items'=>SocialWorkAssessment::with('order.patient')->whereHas('order',fn($q)=>$q->where('sede_id',CurrentSede::id()))->latest('assessment_date')->paginate(20),'pendingOrders'=>Order::with('patient')->where(['sede_id'=>CurrentSede::id(),'attention_type'=>ClinicalService::SOCIAL_WORK])->whereDoesntHave('socialWorkAssessment')->get()]);}
 public function create(Order $order){$this->authorizeOrder($order);return view('social-work.form',['item'=>new SocialWorkAssessment(['assessment_date'=>today()]),'order'=>$order->load('patient')]);}
 public function store(Request $r,Order $order){$this->authorizeOrder($order);$data=$this->validated($r);$item=DB::transaction(function()use($order,$data,$r){$o=Order::lockForUpdate()->findOrFail($order->id);abort_if($o->socialWorkAssessment()->exists(),409);$i=SocialWorkAssessment::create($data+['order_id'=>$o->id,'created_by'=>$r->user()->id,'updated_by'=>$r->user()->id]);$o->update(['status'=>MultisectorialOrderService::COMPLETED,'completed_at'=>now()]);return $i;});return redirect()->route('social-work.show',$item);}
 public function show(SocialWorkAssessment $socialWork){$this->authorizeOrder($socialWork->order);$socialWork->load('order.patient.sede','order.assignedProfessional');return view('social-work.show',['item'=>$socialWork]);}
 public function edit(SocialWorkAssessment $socialWork){$this->authorizeOrder($socialWork->order);return view('social-work.form',['item'=>$socialWork,'order'=>$socialWork->order->load('patient')]);}
 public function update(Request $r,SocialWorkAssessment $socialWork){$this->authorizeOrder($socialWork->order);$d=$this->validated($r);unset($d['assessment_date']);$socialWork->update($d+['updated_by'=>$r->user()->id]);return redirect()->route('social-work.show',$socialWork);}
 public function pdf(SocialWorkAssessment $socialWork,PdfBrandingService $branding){$this->authorizeOrder($socialWork->order);$socialWork->load('order.patient.sede','order.assignedProfessional');return Pdf::loadView('social-work.pdf',$branding->data()+['item'=>$socialWork])->setPaper('a4')->stream("anexo-10-{$socialWork->id}.pdf");}
 private function validated(Request $r){return $r->validate(['assessment_date'=>'required|date','social_evaluation'=>'required|string','family_evaluation'=>'nullable|string','housing_evaluation'=>'nullable|string','employment_evaluation'=>'nullable|string','economic_evaluation'=>'nullable|string','social_diagnosis'=>'required|string','general_measures'=>'nullable|string','specific_measures'=>'nullable|string']);}
 private function authorizeOrder(Order $o){abort_unless($o->attention_type===ClinicalService::SOCIAL_WORK&&(int)$o->sede_id===(int)CurrentSede::id()&&(auth()->user()->can('orders.edit')||(int)$o->assigned_professional_id===(int)auth()->id()),403);}
}
